name: Java CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Build/Test

    runs-on: ubuntu-latest

    strategy:
      matrix:
        java_version: [11, 17]
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK ${{ matrix.java_version }}
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.java_version }}
          server-id: ossrh
          server-username: ${{ secrets.OSSRH_USERNAME }} # username for Sonatype JIRA login
          server-password: ${{ secrets.OSSRH_TOKEN }} # password for Sonatype JIRA login
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }} # Full private key blob
          gpg-passphrase: ${{ secrets.SIGN_KEY_PASS }} # Password chosen when creating the GPG key

      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify

      - name: m2-dump
        run: cat /home/runner/.m2/settings.xml 
      
      - name: Deploy
        run: mvn --batch-mode --update-snapshots deploy
